apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: reactive-tasks-app
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - reactive-tasks
  selector:
    matchLabels:
      app: reactive-tasks-app
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s