spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/tasks
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

app:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topics:
      task-events: ${TASK_EVENTS_TOPIC:task-events}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.springframework.r2dbc: DEBUG